title: 记录生活
author:
  name: shay
  email: 1316625206@qq.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  你好，我是shay。刚刚大学毕业，我对逆向工程、编译原理和图形学感兴趣。
  QQ:1316625206

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: bilibili,        user_url: "https://www.bilibili.com" }
    - { platform: github,         user_url: "https://github.com/shay-520" }
    - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: x,              user_url: "https://bilibili.com" }


# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
mastodon:
 - username: bilibili
   instance: bilibili.com
# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
